name = "lea-liebe-arena-rpg"
servePort = 34872

[tree]
ReplicatedStorage = { 
    Config = "src/ReplicatedStorage/Config.lua", 
    Packages = "Packages",
    Shared = {
        Constants = "src/ReplicatedStorage/Shared/Constants.lua",
        ArenaConstants = "src/ReplicatedStorage/Shared/ArenaConstants.lua",
        Animations = "src/ReplicatedStorage/Shared/Animations.lua",
        SpawnUtils = "src/ReplicatedStorage/Shared/SpawnUtils.lua",
        AchievementFix = "src/ReplicatedStorage/Shared/AchievementFix.lua"
    }
}
ServerScriptService = { 
    GameSetup = "src/ServerScriptService/GameSetup.server.lua",
    ArenaManager = "src/ServerScriptService/ArenaManager.server.lua",
    EnemyAI = "src/ServerScriptService/EnemyAI.lua",
    Main = "src/ServerScriptService/Main.server.lua"
}
StarterPlayer = { 
    StarterPlayerScripts = { 
        AchievementFixLoader = "src/StarterPlayer/StarterPlayerScripts/AchievementFixLoader.client.lua",
        Client = "src/StarterPlayer/StarterPlayerScripts/Client.client.lua"
    } 
}
StarterGui = {
    LobbyUI = "src/StarterGui/LobbyUI.client.lua",
    ArenaHUD = "src/StarterGui/ArenaHUD.client.lua",
    HUD = "src/StarterGui/HUD.client.lua"
}
tests = "test"
