name = "super-mario-game"
servePort = 34872

[tree]
ReplicatedStorage = { Config = "src/ReplicatedStorage/Config.lua", Packages = "Packages" }
ServerScriptService = { GameSetup = "src/ServerScriptService/GameSetup.server.lua" }
StarterPlayer = { StarterPlayerScripts = { PlayerController = "src/StarterPlayer/StarterPlayerScripts/PlayerController.client.lua" } }
tests = "test"
